#!/bin/sh
#
# Shell script for working with the libretranslate API

url=${LIBRETRANSLATE_URL:-"https://translate.argosopentech.com/"}

[ -z "$LIBRETRANSLATE_API_KEY" ] && api_key_flag="-F \"api_key=${LIBRETRANSLATE_API_KEY}\""

curl_args="--silent --show-error "

case "$1" in
	'translate')
		source=$2
    		target=$3
    		q=$4

    		curl -X POST \
            		$curl_args \
            		-F "q=$q" \
            		-F "source=$source" \
            		-F "target=$target" \
	    		$api_key_flag \
            		"${url}translate" ;;
	'detect')
		q=$2
    		curl -X POST \
            		$curl_args \
            		-F "q=$q" \
	    		$api_key_flag \
            		"${url}detect" ;;
	'languages')
		curl -X POST \
            		$curl_args \
            		"${url}languages" ;;
	*) echo 'Invalid function' && exit 1
esac
